name: Build Installer FOMOD C# Plugin

on:
  push:
    branches: master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Build Installer FOMOD C# Plugin
        uses: ModOrganizer2/build-with-mob-action@master
        with:
          mo2-dependencies: cmake_common uibase
